// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflOIn2TQgc_QFzOiB_9fng7y5V2bjrko',
    appId: '1:603308289777:web:ab858d69f621b210fac350',
    messagingSenderId: '603308289777',
    projectId: 'jadurhotel',
    authDomain: 'jadurhotel.firebaseapp.com',
    storageBucket: 'jadurhotel.appspot.com',
    measurementId: 'G-BZEYL6BDZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_zB0pBYXw_GYd6G3gWyzwL07TQ0t5B5o',
    appId: '1:603308289777:android:472a3801100da0b9fac350',
    messagingSenderId: '603308289777',
    projectId: 'jadurhotel',
    storageBucket: 'jadurhotel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1BdBDYE2gEw-mZX-HUSEICgaQiyE7L8',
    appId: '1:603308289777:ios:7438b36c5ae3a55ffac350',
    messagingSenderId: '603308289777',
    projectId: 'jadurhotel',
    storageBucket: 'jadurhotel.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo1BdBDYE2gEw-mZX-HUSEICgaQiyE7L8',
    appId: '1:603308289777:ios:7438b36c5ae3a55ffac350',
    messagingSenderId: '603308289777',
    projectId: 'jadurhotel',
    storageBucket: 'jadurhotel.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCflOIn2TQgc_QFzOiB_9fng7y5V2bjrko',
    appId: '1:603308289777:web:61990df7075ee421fac350',
    messagingSenderId: '603308289777',
    projectId: 'jadurhotel',
    authDomain: 'jadurhotel.firebaseapp.com',
    storageBucket: 'jadurhotel.appspot.com',
    measurementId: 'G-50B4RYRP85',
  );
}
