// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🌐 Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-7G37c2ZZCtWAJIwsuBiPQOjJrkpH7B4',
    authDomain: 'devtriplesteam.firebaseapp.com',
    projectId: 'devtriplesteam',
    storageBucket: 'devtriplesteam.firebasestorage.app',
    messagingSenderId: '277195493362',
    appId: '1:277195493362:web:46dc98305807caf942656b',
    measurementId: 'G-BK4HZPJDPX',
  );

  /// 🤖 Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCELiGd8se4JUb3wHnv-5dv1-YAYXVwnD4',
    appId: '1:325820112512:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '325820112512',
    projectId: 'syed-mahiuddin',
    storageBucket: 'syed-mahiuddin.firebasestorage.app',
  );

  /// 🍎 iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCELiGd8se4JUb3wHnv-5dv1-YAYXVwnD4',
    appId: '1:325820112512:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '325820112512',
    projectId: 'syed-mahiuddin',
    storageBucket: 'syed-mahiuddin.firebasestorage.app',
    iosBundleId: 'com.example.yourbundleid',
  );

  /// 🍎 macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCELiGd8se4JUb3wHnv-5dv1-YAYXVwnD4',
    appId: '1:325820112512:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '325820112512',
    projectId: 'syed-mahiuddin',
    storageBucket: 'syed-mahiuddin.firebasestorage.app',
    iosBundleId: 'com.example.yourbundleid',
  );

  /// 🪟 Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCELiGd8se4JUb3wHnv-5dv1-YAYXVwnD4',
    appId: '1:325820112512:web:e57a8963962ff516ded065',
    messagingSenderId: '325820112512',
    projectId: 'syed-mahiuddin',
    authDomain: 'syed-mahiuddin.firebaseapp.com',
    storageBucket: 'syed-mahiuddin.firebasestorage.app',
    measurementId: 'G-YTKQC9KQMW',
  );
}
